version: '3.8'

services:
  monitor:
    build: ./monitor
    volumes:
      - ./config/monitoring/:/etc/monitoring/configs
      - ./config/notify_group.yaml:/etc/monitoring/notify_group.yaml
      - ./config/config.py:/usr/src/app/config.py
      - ./utils:/usr/lib/monitoring/utils
