#!/bin/sh

http_code=$(curl -o /dev/null ${args} -w '%{http_code}' "${url}" 2>/dev/null)

if [ "${http_code}" -eq "${expected}" ]; then
    echo "${expected} OK!"
    exit 0
else
    echo "Received unexpected HTTP code ${http_code}."
    exit 1  
fi
