nycu-me-https:
  command: '/usr/lib/monitoring/utils/http-check'
  parameters:
    url: "https://nycu.me/"
    args: "-k"
    expected: 200
  interval: 10

nycu-me-https-api:
  command: 'http-check'
  parameters:
    url: "https://nycu.me/api/whoami"
    args: "-k"
    expected: 200
  interval: 10
